G2.ClaimRequest/G2.ClaimRequest.Web/Controllers/UserAdminController.cs
using G2.ClaimRequest.Core.Models;
using G2.ClaimRequest.Web.Mapping;
using G2.ClaimRequest.Web.Models;
using IdentitySample.Models;
using Microsoft.AspNet.Identity.Owin;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace IdentitySample.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersAdminController : Controller
    {
        public UsersAdminController()
        {
        }

        public UsersAdminController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Users/
        [HttpGet]
        public ActionResult Index()
        {
            var listUser = UserManager.Users.ToList();
            var listUserViewModel = new List<StaffViewModel>();
            foreach (var user in listUser)
            {
                listUserViewModel.Add(user.ToModel());
            }
            return View(listUserViewModel.ToList());
        }

        //
        // GET: /Users/Details/5
        [HttpGet]
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);

            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);

            return View(user);
        }

        //
        // GET: /Users/Create
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            //Get the list of Roles
            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }

        //
        // POST: /Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = new Staff { 
                    UserName = userViewModel.Email, 
                    Email = userViewModel.Email, 
                    Department = userViewModel.Department,
                    StaffName = userViewModel.StaffName,
                    JobRank = userViewModel.JobRank,
                    Salary = userViewModel.Salary
                };
                var adminresult = await UserManager.CreateAsync(user, userViewModel.Password);

                //Add User to the selected Roles 
                if (adminresult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                    return View();

                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
            return View();
        }

        //
        // GET: /Users/Edit/1
        [HttpGet]
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var userRoles = await UserManager.GetRolesAsync(user.Id);
            
            return View(new EditUserViewModel()
            {
                Id = user.Id,
                Email = user.Email,
                Department = user.Department,
                JobRank = user.JobRank,
                Salary = user.Salary,
                StaffName = user.StaffName,
                RolesList = RoleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                })
            });
        }

        //
        // POST: /Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Email,Id,StaffName,Department,JobRank,Salary")] EditUserViewModel editUser, params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }

                user.UserName = editUser.Email;
                user.Email = editUser.Email;
                user.StaffName = editUser.StaffName;
                user.Department = editUser.Department;
                user.JobRank = editUser.JobRank;
                user.Salary = editUser.Salary;
                var userRoles = await UserManager.GetRolesAsync(user.Id);

                selectedRole = selectedRole ?? new string[] { };

                var result = await UserManager.AddToRolesAsync(user.Id, selectedRole.Except(userRoles).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                result = await UserManager.RemoveFromRolesAsync(user.Id, userRoles.Except(selectedRole).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something failed.");
            return View();
        }

        //
        // GET: /Users/Delete/5
        [HttpGet]
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user.ToModel());
        }

        //
        // POST: /Users/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var user = await UserManager.FindByIdAsync(id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                var result = await UserManager.DeleteAsync(user);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

G2.ClaimRequest/G2.ClaimRequest.Web/Views/UsersAdmin/Create.cshtml
@model IdentitySample.Models.RegisterViewModel
@{
    ViewBag.Title = "Create Staff";
}

@using (Html.BeginForm("Create", "UsersAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    <div class="card card-custom mb-5 mt-5 mt-sm-0">
        @Html.AntiForgeryToken()
        <div class="card-header p-4">
            <a href="@Url.Action("Index")" class="btn btn-link text-primary font-size-h5"><i class="fas fa-chevron-left"></i>Back</a>
            <button type="submit" class="btn btn-sm btn-success"><i class="fas fa-plus"></i>Create</button>
        </div>
        <div class="card-body px-0 px-sm-4">
            @Html.ValidationSummary("", new { @class = "text-error" })
            <div class="form-group">
                @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
                <div class="col-12 col-md-6">
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
                <div class="col-12 col-md-6">
                    @Html.PasswordFor(m => m.Password, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
                <div class="col-12 col-md-6">
                    @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-2 control-label">
                    Select User Role
                </label>
                <div class="col-12 col-md-6">
                    <div class="checkbox-inline">
                        @foreach (var item in (SelectList)ViewBag.RoleId)
                        {
                            <label class="checkbox"><input type="checkbox" name="SelectedRoles" value="@item.Value"/><span></span>@item.Value</label>
                        }
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StaffName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-12 col-md-6">
                    @Html.EditorFor(model => model.StaffName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.StaffName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-12 col-md-6">
                    @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.JobRank, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-12 col-md-6">
                    @Html.EditorFor(model => model.JobRank, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.JobRank, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-12 col-md-6">
                    @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
                </div>
            </div>
            
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

G2.ClaimRequest/G2.ClaimRequest.Web/Views/UsersAdmin/Delete.cshtml
@model G2.ClaimRequest.Web.Models.StaffViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete.</h2>

<h3>Are you sure you want to delete this User?</h3>
<div>
    <h4>User.</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.StaffName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StaffName)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

G2.ClaimRequest/G2.ClaimRequest.Web/Views/UsersAdmin/Details.cshtml
@model IdentitySample.Models.ApplicationUser

@{
    ViewBag.Title = "Details";
}

<h2>Details.</h2>

<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>
    </dl>
</div>
<h4>List of roles for this user</h4>
@if (ViewBag.RoleNames.Count == 0)
{
    <hr />
    <p>No roles found for this user.</p>
}

<table class="table">

    @foreach (var item in ViewBag.RoleNames)
    {
        <tr>
            <td>
                @item
            </td>
        </tr>
    }
</table>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

G2.ClaimRequest/G2.ClaimRequest.Web/Views/UsersAdmin/Edit.cshtml
@model IdentitySample.Models.EditUserViewModel

@{
    ViewBag.Title = "Edit";
}


@using (Html.BeginForm())
{
    <div class="card card-custom mb-5 mt-5 mt-sm-0">
        @Html.AntiForgeryToken()
        <div class="card-header p-4">
            <a href="@Url.Action("Index")" class="btn btn-link text-primary font-size-h5"><i class="fas fa-chevron-left"></i>Back</a>
            <button type="submit" class="btn btn-sm btn-success">Save</button>
        </div>
        <div class="card-body px-0 px-sm-4">
            <div class="form-horizontal">
                @Html.ValidationSummary(true)
                @Html.HiddenFor(model => model.Id)

                <div class="form-group">
                    @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.Email)
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">
                        Select User Role
                    </label>
                    <div class="col-12 col-md-6">
                        <div class="checkbox-inline">
                            @foreach (var item in Model.RolesList)
                            {
                                <label class="checkbox"><input type="checkbox" name="SelectedRole" value="@item.Value" checked="@item.Selected" /><span></span>@item.Value</label>
                            }
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.StaffName, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-12 col-md-6">
                        @Html.EditorFor(model => model.StaffName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.StaffName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-12 col-md-6">
                        @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.JobRank, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-12 col-md-6">
                        @Html.EditorFor(model => model.JobRank, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.JobRank, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-12 col-md-6">
                        @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
                    </div>
                </div>

                
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

G2.ClaimRequest/G2.ClaimRequest.Web/Views/UsersAdmin/Index.cshtml
@model IEnumerable<G2.ClaimRequest.Web.Models.StaffViewModel>

@{
    ViewBag.Title = "Staff";
}
<div class="card card-custom mb-5 mt-5 mt-sm-0">
    <div class="card-header p-4">
        <a href="@Url.Action("Create")" class="btn btn-success"><i class="fas fa-plus"></i>Create New</a>
    </div>
    <div class="card-body">
        <div class="form-group dataTables_wrapper dt-bootstrap4 no-footer">
            <table class="table table-separate table-head-custom table-checkable dataTable no-footer dtr-inline">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Email)
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => model.StaffName)
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => model.Department)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.JobRank)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Salary)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StaffName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Department)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.JobRank)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Salary)
                        </td>
                        <td>
                            <a href="@Url.Action("Edit", new { id = item.Id})" class="btn btn-clean text-info"><i class='fas fa-edit text-info'></i> Edit</a>
                            <a href="@Url.Action("Delete", new { id = item.Id})" class="btn btn-clean text-danger"><i class='fas fa-trash text-danger'></i> Delete</a>
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</div>